headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/Users/alessioruggera/Desktop/sito_riparazione_elettrodomestici/dist/client"
publishOrigin = "config"
commandOrigin = "ui"
command = "npm run build"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]